on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install West and Dependencies
        run: |
          pip install west
          west init -l config
          west update

      - name: Build Left
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD="felix_left nice_view_adapter"

      - name: Build Right
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD="felix_right nice_view_adapter"

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/*.uf2
